config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show, :new, :create]
  resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: {maximum: 255}
    validates :status, presence: true, inclusion: { in: %w(未着手 進行中 完了 完了と見せかけて放棄) }
    validates :user_id, presence: true
    
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if logged_in?
      @incompleted_tasks = current_user.tasks.where(status: ["未着手","進行中"])
      @completed_tasks = current_user.tasks.where(status: ["完了","完了と見せかけて放棄"])
    end
  end

  def create
    if login
      flash[:success] = "ログインしました。"
      redirect_to root_url
    else
      flash[:danger] = "ログインできませんでした。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] =  "ログアウトしました。(屮´､ゝ`)屮 ｿｸｻｲﾃﾞﾅ"
    redirect_to root_path
  end
  
  private
  
  def login
    email = params[:session][:email]
    password = params[:session][:password]
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :crrect_user,only:[:edit,:show,:update,:destroy]
  
  def create
    @task = current_user.tasks.build(params_task)
    result = @task.save
    move_to_index_with_display_flash(result,:new,"作成")
  end
  
  def new
    @task = current_user.tasks.build
  end
  
  def edit
  end
  
  def show
  end
  
  def update
    result = @task.update(params_task)
    move_to_index_with_display_flash(result,:edit,"変更")
  end
  
  def destroy
    result = @task.destroy
    move_to_index_with_display_flash(result,:show,"削除")
  end
  
  #============================================#
  private
  
  def move_to_index_with_display_flash(result,where_you_were,cud)
    if result
      flash[:success] = "タスクが正常に" + cud + "されました"
      redirect_to "/"
    else
      flash[:danger] = "タスクの" + cud + "に失敗しました"
      render where_you_were
    end
  end
  
  def set_selected_id
    @task = Task.find(params[:id])
  end
  
  def params_task
    params.require(:task).permit(:content,:status)
  end
  
  def crrect_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      flash[:danger] = "氏のタスクでは御座らぬ。"
      redirect_to root_path
    end
  end
  #============================================#
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    require_user_logged_in
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "アカウントを作成しました。ログインして下さい。"
      redirect_to login_url
    else
      flash[:danger] = "アカウント作成に失敗しました。"
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
  def current_user
    if @current_user
      return @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
      return @current_user
    end
  end
  
  def logged_in?
    if current_user
      return true
    else
      return false
    end
  end
  
  def number_of_incompleted_tasks
    incompleted_tasks = current_user.tasks.where(status: ["未着手","進行中"]).count
    if incompleted_tasks > 0
      return incompleted_tasks.to_s + "個が未完了にござる。"
    else
      return "未完了のタスクはござらぬ。"
    end
  end
  
  def number_of_completed_tasks
    completed_tasks = current_user.tasks.where(status: ["完了","完了と見せかけて放棄"]).count
    if completed_tasks > 0
      return "ご苦労であった。"
    else
      return "完了済のタスクはござらぬ。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |key,notice| %>
  <div class="alert alert-<%= key %>" role="alert"><%= notice %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
    
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">タスクリスト</a>
      </div>
  
      <% if logged_in? %>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to '新しいタスクの作成', new_task_path %></li>
            <% mr = current_user.name + "氏のアカウント" %>
            <li><%= link_to mr, user_path(current_user.id) %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      <% end %>
    </div><!-- /.container-fluid -->
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_tasks" %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">

　<div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-xs-12">
　  
    <%= form_for(task) do |f| %>
      
      <div class="form-group">
        <%= f.label :content,label_of_content_form %>
        <%= f.text_field :content, class: "form-control" %>
    
          <%= f.label :status,"ステータスを選択" %>
          <%= f.select :status, ["未着手","進行中","完了","完了と見せかけて放棄"], {} , class: "form-control" %>
    
        <%= f.submit value_of_submit, class: 'btn btn-primary' %>
      </div>
      
    <% end %>

　</div>
</div>

app/views/tasks/_tasks.html.erb
<h1 class="text-center"><%= current_user.name %>氏のタスク一覧</h1>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <h3>未完了のタスク<span class="label label-info"><%= number_of_incompleted_tasks %></span></h3>
    </h3>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th class="text-center">タスク</th>
          <th class="text-center">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% incompleted_tasks.each do |task| %>
          <% if task.status == "未着手" %>
            <% which_status = "active" %>
          <% elsif task.status == "進行中" %>
            <% which_status = "info" %>    
          <% elsif task.status == "完了" %>
            <% which_status = "success" %> 
          <% else %>
            <% which_status = "warning" %> 
          <% end %>
          <tr class=<%= which_status %>>
            <td class="text-center"><%= link_to task.status, task %></td>
            <td class="text-center"><%=link_to task.content, task %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">
      <h3>完了済のタスク<span class="label label-info"><%= number_of_completed_tasks %></span></h3>
    </h3>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th class="text-center">タスク</th>
          <th class="text-center">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% completed_tasks.each do |task| %>
          <% if task.status == "未着手" %>
            <% which_status = "active" %>
          <% elsif task.status == "進行中" %>
            <% which_status = "info" %>    
          <% elsif task.status == "完了" %>
            <% which_status = "success" %> 
          <% else %>
            <% which_status = "warning" %> 
          <% end %>
          <tr class=<%= which_status %>>
            <td class="text-center"><%= link_to task.status, task %></td>
            <td class="text-center"><%=link_to task.content, task %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスク<%= @task.id %>の編集</h1>

<%= 
  render "form", 
    task: @task, 
    label_of_content_form: "タスクを変更",
    value_of_submit: "変更を反映"
%>

app/views/tasks/index.html.erb
<h1>プロニートのタスク一覧</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th class="text-center">id</th>
      <th class="text-center">ステータス</th>
      <th class="text-center">タスク</th>
    </tr>
  </thead>
  <tbody>
    <% @all_tasks.each do |task| %>
      <% if task.status == "未着手" %>
        <% which_status = "active" %>
      <% elsif task.status == "進行中" %>
        <% which_status = "info" %>    
      <% elsif task.status == "完了" %>
        <% which_status = "success" %> 
      <% else %>
        <% which_status = "warning" %> 
      <% end %>
      <tr class=<%= which_status %>>
        <td class="text-right"><%= link_to task.id, task %></td>
        <td class="text-center"><%= task.status %></td>
        <td><%= task.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<button class="btn btn-default" type="submit"><%= link_to "新しいタスクの作成",new_task_path %></button>

app/views/tasks/new.html.erb
<h1>新しいタスクの作成</h1>

<%= 
  render "form", 
    task: @task, 
    label_of_content_form: "タスクを入力",
    value_of_submit: "作成"
%>

app/views/tasks/show.html.erb
<h1>タスク<%= @task.id %>の詳細</h1>

<table class="table table-striped table-bordered">
  <tr>
    <th>ID</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
</table>

<button class="btn btn-default" type="submit"> <%= link_to "タスク一覧に戻る",root_path %> </button>
<button class="btn btn-default" type="submit"> <%= link_to "タスクの編集",edit_task_path %> </button>
<button class="btn btn-danger" type="submit"> <%= link_to "タスクの削除","", method: :delete %> </button>

app/views/users/new.html.erb
<div class="text-center">
  <h1>タスクリストアカウントの作成</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, "パスワードを再入力" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
        
      <%= f.submit "アカウントを作成する", class: "form-control btn btn-primary btn-black" %>
    
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>あなたのアカウント詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>名前</th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
</table>